#index:
#    path: /
#    controller: App\Controller\DefaultController::index
authentication_token:
  path: /authentication_token
  methods: ['POST']

swagger_ui:
  path: /docs
  controller: api_platform.swagger.action.ui

book_post_publication:
  path: /test
  methods: ['GET']
  defaults:
    _controller: App\Controller\TestController::testContrl
